name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asgiref=3.5.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - conda=23.1.0
  - conda-content-trust=0.1.3
  - conda-package-handling=1.9.0
  - django=4.1
  - gunicorn=20.1.0
  - idna=3.4
  - krb5=1.19.4
  - libedit=3.1.20221030
  - libffi=3.4.2
  - libpq=12.9
  - libuuid=1.41.5
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.3.1
  - pluggy=1.0.0
  - psycopg2=2.9.3
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.8
  - readline=8.2
  - requests=2.28.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - sqlparse=0.4.3
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.64.1
  - tzdata=2022g
  - urllib3=1.26.13
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - pip:
      - cryptography==39.0.0
