# Generated by Django 4.1 on 2023-02-14 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('byline', models.CharField(max_length=200, null=True)),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='date published')),
                ('active', models.BinaryField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
